### ISSUE TITLE
About Test_mate.py file 

### ISSUE THREAD

**Issue by yangyangtiaoguo** [ktr-hubrt/MPN#11]
Test_mate.py 代码报错，原因指向
self.weight = Parameter(torch.Tensor(out_features, in_features))
请问作者这两句的变化是什么意思呢，其他文件都是 128
parser.add_argument('--fdim', type=list, default=[512,256,128,64], help='channel dimension of the features')
parser.add_argument('--pdim', type=list, default=[512,256,128,64], help='channel dimension of the prototypes')

**Comment by ktr-hubrt** [comment]
We have modified the codes in test_meta.py
