### ISSUE TITLE
error inside dataloader for Shanghai-Tech dataset

### ISSUE THREAD

**Issue by abhishekaich27** [ktr-hubrt/MPN#12]
Hi,

I am getting the following error when using the Shanghai-Tech dataset:
```
IndexError: list index out of range
1%|          | 405/67748 [03:18<7:00:28,  2.67it/s, Epoch=1 log, Lr=0.000100, PRe=0.006008(0.0218), FRe=0.000619(0.0013), Dist=0.999953(0.0001)] 
```
The error is in this line of file ```model/utils.py``` (inside the ```__getitem__``` block of ```Dataloader```):
```
image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
```
It always occurs at **405**/67748. Can you check it on your end? I am using the default training set of Shanghai-Tech with frames extracted at 24 fps. Thanks in advance.

**Comment by abhishekaich27** [comment]
Figured out the bug. Anyone had this issue, check this: https://github.com/cvlab-yonsei/MNAD/issues/31

**Comment by yinyexingchen** [comment]
> Hi,
> 
> I am getting the following error when using the Shanghai-Tech dataset:
> 
> ```
> IndexError: list index out of range
> 1%|          | 405/67748 [03:18<7:00:28,  2.67it/s, Epoch=1 log, Lr=0.000100, PRe=0.006008(0.0218), FRe=0.000619(0.0013), Dist=0.999953(0.0001)] 
> ```
> 
> The error is in this line of file `model/utils.py` (inside the `__getitem__` block of `Dataloader`):
> 
> ```
> image = np_load_frame(self.videos[video_name]['frame'][frame_name+i], self._resize_height, self._resize_width)
> ```
> 
> It always occurs at **405**/67748. Can you check it on your end? I am using the default training set of Shanghai-Tech with frames extracted at 24 fps. Thanks in advance.

hello bro how do you slove this problem ,can you share the code?and how many frames you use in shanghai,I see that 67748
