### ISSUE TITLE
calculate the prototype after decoding process?

### ISSUE THREAD

**Issue by BenedictGreen** [ktr-hubrt/MPN#13]
Thx for the great work!
I read the code 'base_model.py', in function forward() at line146,  I noticed that the code calculated the prototype after decoding process instead of after the encoding process. I read the ori paper with figure 2,which seems that the calculation of the prototype is after encoding process.I am confused. Could you tell me which situation is correct?
```
    def forward(self, x, weights=None, train=True):
        ...
        fea, skip1, skip2, skip3 = self.encoder(x) 
        new_fea = self.decoder(fea, skip1, skip2, skip3) 
        ....
        new_fea = F.normalize(new_fea, dim=1)
        updated_fea, keys, fea_loss, cst_loss, dis_loss = self.prototype(new_fea, new_fea, weights, train)
        output = self.ohead(updated_fea)
```

**Comment by ktr-hubrt** [comment]
here, the self.decoder is the part of AE model, not the decoding op of prototypes
