### ISSUE TITLE
Could you pls upload the model trained on ShanghaiTech and Avenue? 

### ISSUE THREAD

**Issue by BenedictGreen** [ktr-hubrt/MPN#14]
Thx a lot!
I retrained the model on two datasets, but did not get the same results as in the paper. Could you pls upload the model trained on ShanghaiTech and Avenue? Or provide more detailed parameters for the training settings.

**Comment by yangyangtiaoguo** [comment]
This code is hard to change.

**Comment by yangyangtiaoguo** [comment]
Avenue I got 82.5 AUC.in 300 epoch

**Comment by BenedictGreen** [comment]
I retrain the model on three datasets and got 95.2% auc on Ped2 with 60 epochs; 82.64% on Avenue with 60 epochs; 66.2% on SHTech with 10 epochs, all the results were lower than paper's. I don’t know which tricks were not used that resulted in poor results

**Comment by wenxiaopeng-del** [comment]
I was wondering if there is a trained model to test test_meta.py @BenedictGreen

**Comment by BenedictGreen** [comment]
I only retrain the model with the code 'Train,py',  the official codes seems to only provide the trained model on Ped2 under the unsupervised setting, but did not provide a model trained  under the few-shot setting.

**Comment by wenxiaopeng-del** [comment]
Thank you very much. I would also like to ask where can I get the pre-trained AE model mentioned in the paper @BenedictGreen

**Comment by wenxiaopeng-del** [comment]
Thank you very much. I would also like to ask where can I get the pre-trained AE model mentioned in the paper




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月14日(星期三) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ktr-hubrt/MPN] Could you pls upload the model trained on ShanghaiTech and Avenue?  (#14)






我只用代码‘ Train ， py ’对模型进行了重新训练，官方代码似乎只提供了 Ped 2 上在无监督设置下训练的模型，而没有提供在少数镜头设置下的训练模型。

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.

**Comment by BenedictGreen** [comment]
in README.md. "We have uploaded our model trained on Ped2 to Baidunetdisk(link：https://pan.baidu.com/s/1I2QRMPJtnvhXozGa3s2-pg code：6jmg)."

**Comment by ktr-hubrt** [comment]
you can try a higher balance weight for feature anomaly score, cause these scores are more robust

**Comment by BenedictGreen** [comment]
Thank you for your reply! It would be very grateful if you can upload the model trained on SHTech and Avenue.

**Comment by zzzzyq-18** [comment]
> 感谢你的回复！如果您能上传在上海科技和大道上训练的模型，将不胜感激。

Hello, may I have your repetition now? I met the same problem with you

**Comment by yinyexingchen** [comment]
> Thx a lot! I retrained the model on two datasets, but did not get the same results as in the paper. Could you pls upload the model trained on ShanghaiTech and Avenue? Or provide more detailed parameters for the training settings.

Hello, the training set of Shanghai  is video. How do you deal with it? Thanks a lot
