### ISSUE TITLE
Pretrained models on Drive/OneDrive/DropBox

### ISSUE THREAD

**Issue by abhishekaich27** [ktr-hubrt/MPN#17]
Hi, 

Can you please make the pretrained models on Google Drive/OneDrive/DropBox? We can't access baidu from my current location,

**Comment by ktr-hubrt** [comment]
im trying

**Comment by abhishekaich27** [comment]
Hi @ktr-hubrt! Thanks for uploading the models to Google Drive. Please set this Google Drive link as public so that we can access it without requesting access.
