### ISSUE TITLE
ones needs to be contiguous

### ISSUE THREAD

**Issue by wenxiaopeng-del** [ktr-hubrt/MPN#18]
The problem I encountered when running train.py was not solved. I also use torch.autograd.detect_anomaly() to find some reasons.Here's the hint is 'No forward pass information available. Enable detect anomaly during forward pass for more information
<img width="586" alt="error" src="https://user-images.githubusercontent.com/61273910/128166964-3d2bcd5e-bc52-4169-ae60-722aafffbd0a.png">

**Comment by ktr-hubrt** [comment]
show me the detailed error trace

**Comment by wenxiaopeng-del** [comment]
<img width="815" alt="error" src="https://user-images.githubusercontent.com/61273910/128520606-311a606e-7e56-4811-9bc2-4d58337daa2b.png">

**Comment by ktr-hubrt** [comment]
please make sure you are running the newest codes and your environment is correct. i have not met your problem
