### ISSUE TITLE
Few shot folder in Google Drive seems empty

### ISSUE THREAD

**Issue by abhishekaich27** [ktr-hubrt/MPN#19]
Hi,

Your google Drive folder named 'few-shot' seem empty. I can definitely see a model under 'unsupervised' folder.

Can you please check?

**Comment by ktr-hubrt** [comment]
sorry, im realy busy recently, i will make public the models as soon as possible.

**Comment by wangmiaowei** [comment]
Warning! IT IS IN 2022 YEAR! I still get the weights file
