### ISSUE TITLE
Location of MPN

### ISSUE THREAD

**Issue by abhishekaich27** [ktr-hubrt/MPN#24]
According to you paper, MPN seems to be at bottleneck of encoder and decoder but according to your code it seems to be after decoder. Can you please clarify ?

**Comment by ktr-hubrt** [comment]
In paper the encoder means the whole AE

**Comment by abhishekaich27** [comment]
Thanks for quick response. Just to be sure, the structure of your model is as follows: 

Encoder -> DPU -> Decoder?

**Comment by ktr-hubrt** [comment]
In detail, Encoder( Deep AE) -> DPU -> Decoder(out head)
