### ISSUE TITLE
preprocessed?

### ISSUE THREAD

**Issue by Tuanzhang911** [ktr-hubrt/MPN#25]
Does the UCSD data set need to be preprocessed?

**Comment by abhishekaich27** [comment]
@ktr-hubrt Why have you provided the `data` folder? I see that it contains the GT files for datasets whose files are already publically available. Have you corrected any labels or is it just to facilitate the data-loading process?

**Comment by Tuanzhang911** [comment]
> @ktr-hubrt Why have you provided the `data` folder? I see that it contains the GT files for these datasets are already publically available (although in a different format). Have you corrected any labels or is it just to facilitate the data-loading process?

I mean when I put the UCSD dataset (open online) into the data folder you created, the program doesn't work, I can see that the UCSD image format is TIF and the data processing format you provided is GIF.  I am a little confused and hope to get your help.  --------- a foundation student

**Comment by Tuanzhang911** [comment]
> > @ktr-hubrt Why have you provided the `data` folder? I see that it contains the GT files for these datasets are already publically available (although in a different format). Have you corrected any labels or is it just to facilitate the data-loading process?
> 
>Just now, when I looked at readme again, I realized my misunderstanding of you.
 I am very sorry！Wish you happy life.

**Comment by ktr-hubrt** [comment]
> @ktr-hubrt Why have you provided the `data` folder? I see that it contains the GT files for these datasets are already publically available (although in a different format). Have you corrected any labels or is it just to facilitate the data-loading process?

it is used for loading speed up
