### ISSUE TITLE
Test_meta.py script doesn't work

### ISSUE THREAD

**Issue by WooXinyi** [ktr-hubrt/MPN#5]
Thanks for your nice work!
But test_meta.py script doesn't work when testing on ped2, could you please fix it? thanks.

![微信图片_20210526170100](https://user-images.githubusercontent.com/31875617/119634214-19cfc600-be45-11eb-968e-022e832f3935.jpg)

**Comment by ktr-hubrt** [comment]
Thank you for your attention.
We have modified the codes in test_meta.py and base_model.py

**Comment by wenxiaopeng-del** [comment]
Hello, may I ask if you have reproduced this excellent paper completely? When I was testing the model uploaded by the author, I met some problems. I think the problem might be the folder with the name of data.Can I have a look at your data content?

**Comment by wenxiaopeng-del** [comment]
Hello, may I ask if you have reproduced this excellent paper completely? When I was testing the model uploaded by the author, I met some problems. I think the problem might be the folder with the name of data.Can I have a look at your data content? @WooXinyi

**Comment by wenxiaopeng-del** [comment]
What is the test model for test_meta.py? @WooXinyi
